<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>

<script>

    window.onload = function () {
        // function test() {
        //     return new Promise((resolve, reject) => {
        //         console.log(1);
        //         setTimeout(() => {
        //             console.log(2);
        //             resolve()
        //         }, 2000)
        //     })
        // }

        // test().then(() => {
        //     // setTimeout(() => {   // then 并不会等这里面的异步操作完在进行下一步操作
        //     //     console.log(3);
        //     //     setTimeout(() => {
        //     //         console.log(4);
        //     //     }, 2000)
        //     // }, 1000)

        //     return new Promise((resolve, reject) => {
        //         setTimeout(() => {   // then 并不会等这里面的异步操作完在进行下一步操作
        //             console.log(3);
        //             resolve()
        //             setTimeout(() => {
        //                 console.log(4);
        //             }, 2000)
        //         }, 1000)
        //     })
        // }).then(() => {
        //     setTimeout(() => {
        //         console.log(5);
        //     }, 0)
        // })



        function test2() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    console.log(1);
                    resolve()
                }, 3000)
            })
        }

        // 这样写可以正确的返回1,2,3,4,5 如果.then() 没有返回promise时 只有传值的作用 没有处理异步的作用 必须配和resolve和reject才能实现连续的异步操作
        // 因为只有return new promise的时候，去调用resolve,reject后· 后续的.then才会被推入到微队列 不然是不会执行的
        test2().then(() => {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    console.log(2);
                    return new Promise((ro, rj) => {
                        setTimeout(() => {
                            console.log(3);
                            ro()
                        }, 2000)
                    }).then(() => {
                        setTimeout(() => {
                            console.log(4)
                            resolve();
                        }, 1500)
                    })

                }, 1000)
            })
        }).then(() => {
            console.log(5); // 如果不执行后续不执行异步操作的话 then可以不用返回new promise
        }).catch(() => {
            console.log("执行失败了");
        }).finally(() => {
            console.log("finally ==> 不管成功失败都会去执行的") // 这个会比5先输出 因为它被推入微队列 而5被推入到宏队列
        })
    }
</script>

</html>